//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public string Numero { get; set; }
        public string Referant { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
